name: in_app_purchases_intl
description: Intl Package for common translations in your In App Purchase App. made by www.linkfive.io
version: 1.0.0
homepage: https://github.com/LinkFive/flutter-in_app_purchases_paywall
repository: https://github.com/LinkFive/flutter-in_app_purchases_paywall

environment:
  sdk: ^3.0.0
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.1.0

flutter:
  generate: true